import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Phase12-Dark A2: 初回描画前に data-theme を確定（SSR 安全）。
 * 解決ロジックは docs/118 A4 契約に従い、src/lib/theme.ts の resolveTheme() と同一分岐で複製している。
 * 契約変更時は theme.ts とこの script の両方を同じ分岐に揃えること。
 */
const THEME_INIT_SCRIPT = `
(function(){
  var key = 'kuharaos.theme';
  var theme = 'light';
  try {
    var stored = typeof localStorage !== 'undefined' && localStorage.getItem(key);
    if (stored === 'light' || stored === 'dark') { theme = stored; }
    else if (typeof window !== 'undefined' && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) { theme = 'dark'; }
  } catch (e) {}
  try { document.documentElement.setAttribute('data-theme', theme); } catch (e) {}
})();
`;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
        {children}
      </body>
    </html>
  );
}
